## 3. CRUD Notebook: CREATE, NOT LIKE, LIKE, NOT NULL, NULL, IS, INSERT, UPDATE, DELETE, DROP TABLE
Create, Read, Update, and Delete, the database staples.

This workbook covers how to **Create** tables and add data, **Read** data, **Update** that data and then how to **Delete** data and tables.

Also covered are a few more useful keywords pertaining to tables including NULL and NOT NULL. With NOT LIKE and LIKE being included to expand on your filtering knowledge.

###### Keywords Covered - CREATE, NOT LIKE, LIKE, NOT NULL, NULL, IS, INSERT, UPDATE, DELETE, DROP TABLE

In [1]:
import sqlite3
import pandas as pd

# Connect to database
data_conn = sqlite3.connect("pokemon.db")

### Creating Tables and Data

#### CREATE

Use: Creating a new table.

Below we will demonstrate how to create a simple new table.

In [2]:
data_conn.execute("CREATE TABLE pokemon_moves (name TEXT NOT NULL, Type TEXT NOT NULL, damage INTEGER NOT NULL)")

#### Not Like

Use: Filtering for rows that DO NOT match a pattern.

*Tip: Opposite of LIKE.*

In [3]:
# We can see below that the table has been added to the database. The sqlite_ tables are excluded with NOT LIKE.
tables = data_conn.execute("SELECT name FROM pragma_table_list WHERE type = 'table' AND name NOT LIKE 'sqlite_%'").fetchall()
for table in tables:
    print(table[0])

pokemon_moves
votes
pokemon
users

#### Like

Use: Filtering for rows that match a pattern.

*Tip: See below for useful Wildcard characters:*

*    *% = Zero or more characters.*
      
*    *_ = Exactly one character.*
      
*    *%_% = At least one character.*

In [4]:
# Using the opposite of LIKE, NOT LIKE we can see only the sqlite_ tables.
tables = data_conn.execute("SELECT name FROM pragma_table_list WHERE type = 'table' AND name LIKE 'sqlite%'").fetchall()
for table in tables:
    print(table[0])

sqlite_sequence
sqlite_schema
sqlite_temp_schema

#### NOT NULL

You may have noticed we used NOT NULL for each of our column names.
                                     
Use: Ensuring that an entry cannot be left blank. These fields are mandatory.

*Tip: If not NOT NULL, then a value of NULL can be used.*

#### NULL

Use: An empty value. Not the same as zero.

#### IS

Use: Instead of = or !=, use IS NULL or IS NOT NULL for comparison purposes in WHERE statements.

e.g. "SELECT * FROM pokemon WHERE name IS NOT NULL" to select all Pokemon with names.

#### INSERT

Use: Inserting data into a table.

*Tip: Multiple rows can be added at once.*

Below we will insert a move into the new table.

In [5]:
# Inserting one move.
data_conn.execute("INSERT INTO pokemon_moves (name, type, damage) VALUES \
                ('Ice Beam', 'Ice', 60)")

In [6]:
# Inserting several moves at once.
data_conn.execute("INSERT INTO pokemon_moves (name, type, damage) VALUES \
                ('Fire Blast', 'Fire', 120), \
                ('Surf', 'Water', 85), \
                ('Tackle', 'Normal', 20)")

### Reading Data

We have already covered the SELECT keyword to read data, we will use this now to view what we have done.

In [7]:
pkmn_moves = data_conn.execute("SELECT * FROM pokemon_moves").fetchall()
pd.DataFrame(pkmn_moves)

            0       1    2
0    Ice Beam     Ice   60
1  Fire Blast    Fire  120
2        Surf   Water   85
3      Tackle  Normal   20

### Updating Data

#### UPDATE

Use: Updatating data.

#### SET

Use: Specifying which columns to update.

*WARNING: ALWAYS USE **WHERE** OR YOU WILL UPDATE EVERY SINGLE ROW IN THE TABLE.*

In [8]:
# Update the name of the move Ice beam to Bubble Beam.
data_conn.execute("UPDATE pokemon_moves SET name = 'Bubble Beam' WHERE name = 'Ice Beam'")

# View the table to see the change.
pkmn_moves = data_conn.execute("SELECT * FROM pokemon_moves").fetchall()
pd.DataFrame(pkmn_moves)

             0       1    2
0  Bubble Beam     Ice   60
1   Fire Blast    Fire  120
2         Surf   Water   85
3       Tackle  Normal   20

### Deleting Data

#### DELETE

Use: Deleting Data.

*WARNING: ALWAYS USE **WHERE** OR YOU WILL **DELETE** UPDATE EVERYTHING.*

Below we will delete the move Tackle from the moves table.

In [9]:
# Delete the move Tackle from the pokemon_moves table.
data_conn.execute("DELETE FROM pokemon_moves WHERE name = 'Tackle'")

# View the table to see the change.
pkmn_moves = data_conn.execute("SELECT * FROM pokemon_moves").fetchall()
pd.DataFrame(pkmn_moves)

             0      1    2
0  Bubble Beam    Ice   60
1   Fire Blast   Fire  120
2         Surf  Water   85

#### DROP TABLE

Use: Deleting a table.

*Tip: Permanent, so don't do it lightly.*

In [10]:
# View the table (perhaps?) to see the change.
pkmn_moves = data_conn.execute("SELECT * FROM pokemon_moves").fetchall()
pd.DataFrame(pkmn_moves)

OperationalError: no such table: pokemon_moves

The table has been deleted.