## 8. String Functions: CONCAT, CONCAT_WS, LENGTH, CHAR_LENGTH, LEN, SUBSTR, SUBSTRING, RIGHT, LEFT, UPPER, LOWER, INITCAP, TRIM, LTRIM, RTRIM, REPLACE, INSTR, CHARINDEX, POSITION, LOCATE

In this notebook we will cover functions to modify, search and measure strings in various ways..

Also the use of triple quotations *""" """* in writing SQL and the Pandas *read_sql* function.

###### Keywords Covered - CONCAT, CONCAT_WS, LENGTH, CHAR_LENGTH, LEN, SUBSTR, SUBSTRING, RIGHT, LEFT, UPPER, LOWER, INITCAP, TRIM, LTRIM, RTRIM, REPLACE, INSTR, CHARINDEX, POSITION, LOCATE

In [1]:
import sqlite3
import pandas as pd

# Connect to database
data_conn = sqlite3.connect("pokemon.db")

data_conn.execute("DROP TABLE pokemon_items") # Delete to refresh any prior changes.

data_conn.execute("CREATE TABLE pokemon_items \
                        (name TEXT NOT NULL, \
                         effect TEXT)")

data_conn.execute("INSERT INTO pokemon_items (name, effect) VALUES \
                ('Poké Ball', 'Catches Pokémon.'), ('great Ball', 'Catches Pokémon better.'), ('Ultra Ball', 'Catches Pokémon great!'), \
                ('potion', NULL), ('Super Potion', 'Heals 50 HP.'), ('Full Restore', NULL), \
                ('revive', 'Revives your Pokémon.'), ('Escape Rope', 'Takes you to the entrance of a cave.')")

#### CONCAT

Use: Concatenation of two or more strings.

*Tip: Can also use double pipe operator || or + symbol. Double pipe operator returns NULL if you attempt to concatonate any NULL values.*

#### """ """


Use: You don't have to use \ at the end of each line.

In [2]:
df = pd.DataFrame(data_conn.execute("""SELECT CONCAT(name, ": ", effect)
                                       FROM pokemon_items""").fetchall())
df.columns = ["CONCAT(name, ': ', effect)"]
df

                          CONCAT(name, ': ', effect)
0                        Poké Ball: Catches Pokémon.
1                great Ball: Catches Pokémon better.
2                 Ultra Ball: Catches Pokémon great!
3                                           potion:
4                         Super Potion: Heals 50 HP.
5                                     Full Restore:
6                      revive: Revives your Pokémon.
7  Escape Rope: Takes you to the entrance of a cave.

We can do the same thing by using the ***read_sql(sql=[SQL], con=[Connection])*** Pandas function. This function passes the column names straight into the dataframe, skipping the process of adding the column names as we were doing before.

In [3]:
pd.read_sql(sql="""SELECT name || ': ' || effect 
                   FROM pokemon_items""", con=data_conn)

                              name || ': ' || effect
0                        Poké Ball: Catches Pokémon.
1                great Ball: Catches Pokémon better.
2                 Ultra Ball: Catches Pokémon great!
3                                                NaN
4                         Super Potion: Heals 50 HP.
5                                                NaN
6                      revive: Revives your Pokémon.
7  Escape Rope: Takes you to the entrance of a cave.

#### CONCAT_WS

Use: Concatonation with a seperator.

*Tip: Skips NULL values automatically like CONCAT.*

Below we will use ": " as the seperator, instead of it being an additional concatonation term.
This is more useful for longer lists.

In [4]:
pd.read_sql(sql="""SELECT CONCAT_WS(": ", name,  effect) 
                   FROM pokemon_items""", con=data_conn)

                      CONCAT_WS(": ", name,  effect)
0                        Poké Ball: Catches Pokémon.
1                great Ball: Catches Pokémon better.
2                 Ultra Ball: Catches Pokémon great!
3                                             potion
4                         Super Potion: Heals 50 HP.
5                                       Full Restore
6                      revive: Revives your Pokémon.
7  Escape Rope: Takes you to the entrance of a cave.

#### LENGTH (CHAR_LENGTH or LEN in other SQL varieties)

Use: Tell a user the length of a string.

In [5]:
pd.read_sql(sql="""SELECT name, LENGTH(name)
                   FROM pokemon_items""", con=data_conn)

           name  LENGTH(name)
0     Poké Ball             9
1    great Ball            10
2    Ultra Ball            10
3        potion             6
4  Super Potion            12
5  Full Restore            12
6        revive             6
7   Escape Rope            11

#### SUBSTR SUBSTRING

Use: Extracting a portion of a string.

*Syntax: SUBSTR(string, start, length) (same for SUBSTRING).*

*Tip: Start is 1, not 0 for the first character in a string.*

RIGHT and left are in not in SQLite, but in other variants. You can make an equivelant using SUBSTR and LENGTH (to see how long the string is) in SQLite.

#### RIGHT

Use: Selecting some of the characters form the Right of a a string.

*Syntax: RIGHT(string, length).*

#### LEFT

Use: Selecting some of the characters form the Left of a a string.

*Syntax: LEFT(string, length).*

In [6]:
pd.read_sql(sql="""SELECT name, SUBSTR(name, 1, 4), SUBSTRING(name, 5, 10) 
                   FROM pokemon_items""", con=data_conn)

           name SUBSTR(name, 1, 4) SUBSTRING(name, 5, 10)
0     Poké Ball               Poké                   Ball
1    great Ball               grea                 t Ball
2    Ultra Ball               Ultr                 a Ball
3        potion               poti                     on
4  Super Potion               Supe               r Potion
5  Full Restore               Full                Restore
6        revive               revi                     ve
7   Escape Rope               Esca                pe Rope

#### UPPER

Use: Makes the whole string uppercase.

#### LOWER

Use: Makes whole string lowerrcase.

#### INITCAP (not in SQLite)

Use: Capitalises the first letter of every word in a string and converts all other letters to lowercase

See below where we make the first letter of each string uppercase. Useful for name or company fields.

In [7]:
pd.read_sql(sql="""SELECT name, UPPER(name),
                                LOWER(name),
                                CONCAT(UPPER(SUBSTR(name, 1, 1)), LOWER(SUBSTR(name, 2, 151)))
                                FROM pokemon_items""", con=data_conn)

,name,UPPER(name),LOWER(name),"CONCAT(UPPER(SUBSTR(name, 1, 1)), LOWER(SUBSTR(name, 2, 151)))"
0,Poké Ball,POKé BALL,poké ball,Poké ball
1,great Ball,GREAT BALL,great ball,Great ball
2,Ultra Ball,ULTRA BALL,ultra ball,Ultra ball
3,potion,POTION,potion,Potion
4,Super Potion,SUPER POTION,super potion,Super potion
5,Full Restore,FULL RESTORE,full restore,Full restore
6,revive,REVIVE,revive,Revive
7,Escape Rope,ESCAPE ROPE,escape rope,Escape rope

#### TRIM

Use: Trimming white space or characters from both sides of a string. 

*Syntax: Use TRIM(string, char) to delete a specific character (or characters) - Same with LTRIM and RTRIM.*

#### LTRIM

Use: Trimming white space or characters from the left side of a string. 

#### RTRIM

Use: Trimming white space or characters from the right side of a string. 

Below we will demonstrate all three, trimming firstly just whitespace, then specific characters.

In [8]:
pd.read_sql(sql="""SELECT TRIM('   Ash     '),
                   LTRIM('.!.Misty', '.!'),
                   RTRIM('Brock!!!', '!')""", con=data_conn)

  TRIM('   Ash     ') LTRIM('.!.Misty', '.!') RTRIM('Brock!!!', '!')
0                 Ash                   Misty                  Brock

#### REPLACE

Use: Replaces all occurences of a substring with another string.

*Tip: Learn it well as it is very useful for data cleaning.*

In [9]:
# Replacing Poké with Digi.
pd.read_sql(sql="""SELECT name, REPLACE(name, 'Poké', 'Digi'),
                                REPLACE(effect, 'Poké', 'Digi')
                                FROM pokemon_items""", con=data_conn)

,name,"REPLACE(name, 'Poké', 'Digi')","REPLACE(effect, 'Poké', 'Digi')"
0,Poké Ball,Digi Ball,Catches Digimon.
1,great Ball,great Ball,Catches Digimon better.
2,Ultra Ball,Ultra Ball,Catches Digimon great!
3,potion,potion,NaN
4,Super Potion,Super Potion,Heals 50 HP.
5,Full Restore,Full Restore,NaN
6,revive,revive,Revives your Digimon.
7,Escape Rope,Escape Rope,Takes you to the entrance of a cave.

#### INSTR 

Use:  Finding the position of a substring (count starts at 1 for first letter).

*Syntax: INSTR(string, substring)*

*Tip: Returns NULL if string or substring are NULL*

#### CHARINDEX POSITION LOCATE 

Use: Same as INSTR but used in MYSQL and other SQL database languages.

These substring tools can be useful to to parse strings by finding delimiters.

Below we will use INSTR to find the spaces to get the first word of each name.

Note, we add a space to name [INSTR(name || ' '] to find a space at the end of the one word items, else INSTR would return 0, as they have no spaces.

In [10]:
# Replacing Poké with Digi.
pd.read_sql(sql="""SELECT name,
                        INSTR(name, ' '),
                        SUBSTR(name, 1, INSTR(name || ' ', ' ')-1)
                        FROM pokemon_items""", con=data_conn)

           name  INSTR(name, ' ') SUBSTR(name, 1, INSTR(name || ' ', ' ')-1)
0     Poké Ball                 5                                       Poké
1    great Ball                 6                                      great
2    Ultra Ball                 6                                      Ultra
3        potion                 0                                     potion
4  Super Potion                 6                                      Super
5  Full Restore                 5                                       Full
6        revive                 0                                     revive
7   Escape Rope                 7                                     Escape